package com.sap.eshop.dao;
// Generated Dec 9, 2015 12:38:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private int id;
	private String name;
	private String password;
	private Integer level;

	public Admin() {
	}

	public Admin(int id) {
		this.id = id;
	}

	public Admin(int id, String name, String password, Integer level) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.level = level;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

}
