package com.sap.eshop.dao;
// Generated Dec 9, 2015 12:38:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String custName;
	private int custMobile;
	private String custPhone;
	private String custAddr;
	private int status;
	private Date time;
	private String comments;

	public Order() {
	}

	public Order(Product product, String custName, int custMobile, String custAddr, int status, Date time) {
		this.product = product;
		this.custName = custName;
		this.custMobile = custMobile;
		this.custAddr = custAddr;
		this.status = status;
		this.time = time;
	}

	public Order(Product product, String custName, int custMobile, String custPhone, String custAddr, int status,
			Date time, String comments) {
		this.product = product;
		this.custName = custName;
		this.custMobile = custMobile;
		this.custPhone = custPhone;
		this.custAddr = custAddr;
		this.status = status;
		this.time = time;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public int getCustMobile() {
		return this.custMobile;
	}

	public void setCustMobile(int custMobile) {
		this.custMobile = custMobile;
	}

	public String getCustPhone() {
		return this.custPhone;
	}

	public void setCustPhone(String custPhone) {
		this.custPhone = custPhone;
	}

	public String getCustAddr() {
		return this.custAddr;
	}

	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
