package com.sap.eshop.dao;
// Generated Dec 9, 2015 12:38:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Product> products = new HashSet<Product>(0);

	public ProductType() {
	}

	public ProductType(String name) {
		this.name = name;
	}

	public ProductType(String name, Set<Product> products) {
		this.name = name;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
