package com.sap.eshop.dao;
// Generated Dec 9, 2015 12:38:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private ProductType productType;
	private String name;
	private String description;
	private String smallImg;
	private String bigImg;
	private double price;
	private String param1;
	private String param2;
	private String param3;
	private Set<Order> orders = new HashSet<Order>(0);

	public Product() {
	}

	public Product(ProductType productType, String name, double price) {
		this.productType = productType;
		this.name = name;
		this.price = price;
	}

	public Product(ProductType productType, String name, String description, String smallImg, String bigImg,
			double price, String param1, String param2, String param3, Set<Order> orders) {
		this.productType = productType;
		this.name = name;
		this.description = description;
		this.smallImg = smallImg;
		this.bigImg = bigImg;
		this.price = price;
		this.param1 = param1;
		this.param2 = param2;
		this.param3 = param3;
		this.orders = orders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductType getProductType() {
		return this.productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSmallImg() {
		return this.smallImg;
	}

	public void setSmallImg(String smallImg) {
		this.smallImg = smallImg;
	}

	public String getBigImg() {
		return this.bigImg;
	}

	public void setBigImg(String bigImg) {
		this.bigImg = bigImg;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getParam1() {
		return this.param1;
	}

	public void setParam1(String param1) {
		this.param1 = param1;
	}

	public String getParam2() {
		return this.param2;
	}

	public void setParam2(String param2) {
		this.param2 = param2;
	}

	public String getParam3() {
		return this.param3;
	}

	public void setParam3(String param3) {
		this.param3 = param3;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
