package com.sap.eshop.dao;
// Generated Dec 9, 2015 12:38:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String account;
	private String password;
	private String name;
	private int mobile;
	private String phone;
	private String email;
	private String address;
	private String sex;
	private Date birthday;
	private Date regTime;

	public User() {
	}

	public User(String account, String name, int mobile, String email, Date regTime) {
		this.account = account;
		this.name = name;
		this.mobile = mobile;
		this.email = email;
		this.regTime = regTime;
	}

	public User(String account, String password, String name, int mobile, String phone, String email, String address,
			String sex, Date birthday, Date regTime) {
		this.account = account;
		this.password = password;
		this.name = name;
		this.mobile = mobile;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.sex = sex;
		this.birthday = birthday;
		this.regTime = regTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getMobile() {
		return this.mobile;
	}

	public void setMobile(int mobile) {
		this.mobile = mobile;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getRegTime() {
		return this.regTime;
	}

	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

}
